### ISSUE TITLE
Nuke Timer carries on into next round

### ISSUE THREAD

**Issue by Jakey-F** [TheVoidNebula/Nukes#2]
As the title says. If the nuke isn't triggered in one round, it will continue counting down in the next round as well, which can result in the nuke being activated within minutes of a round starting.

I'm not sure if I'm missing anything here, but I can't seem to have the timer stop/reset when a round is ended.
This seems to happen with both Quick Round Restart on and off.

**Comment by TheVoidNebula** [comment]
Ah thank you for reporting this bug, I looked through the code and found the issue!
It should be fixed in the next release!
